apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-bubble-hpa
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-bubble-deployment
  targetCPUUtilizationPercentage: 20
