apiVersion: v1
kind: Service
metadata:
  name: node-bubble-service
spec:
  type: LoadBalancer
  ports:
  - nodePort: 30000
    port: 8081
    targetPort: 8080
  selector:
    app: node-bubble-deployment
